### ISSUE TITLE
option to disable webfonts?

### ISSUE THREAD

**Issue by cardi** [davidhampgonsalves/hugo-black-and-light-theme#12]
Great theme!

What do you think of using a conditional to disable web fonts via `config.toml` (if you prefer to have web fonts enabled by default)?

e.g., from:
https://github.com/davidhampgonsalves/hugo-black-and-light-theme/blob/3884985737ebc654314a372914e11a27d666c7b9/layouts/partials/header.html#L12

to something like:

```html
{{ if not .Site.Params.disableWebFonts }}
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400|Old+Standard+TT:400' rel='stylesheet' type='text/css'>
{{ end }}
```

Thus a site can have its web fonts disabled explicitly.

**Comment by davidhampgonsalves** [comment]
Yea good idea, the disableWebFonts param is now on master.

**Comment by cardi** [comment]
Great, thanks!
