### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by ghost** [davidhampgonsalves/hugo-black-and-light-theme#14]
Hi, I was wondering if there is a method to change the syntax highlighting for code chunks (R and Python). 

I'm using the Blogdown package and have been looking at some of the solutions that other people have tried with different themes, [here](https://stackoverflow.com/questions/38821339/hugo-pygments-how-to-change-highlighting-theme) and [here](https://amber.rbind.io/blog/2017/11/15/syntax-highlighting/). 

However, Black & White does not follow the same file structure as the themes in these examples so I couldn't get them to work. Is there something else that I may not be aware of that I could try? (I'm not a developer so navigating this stuff is a bit confusing atm). Thanks for any help and for the theme.

**Comment by cardi** [comment]
I'm not familiar with Blogdown, but Hugo comes with [syntax highlighting](https://gohugo.io/content-management/syntax-highlighting/) built-in. Additionally, this particular theme doesn't override or prevent syntax highlighting.

In your `config.toml`, add the following lines (I'm using Hugo 0.50):
```toml
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsStyle      = "colorful"
```

(a full list of built-in styles is [here](https://help.farbox.com/pygments.html))

Then, in the `.md` file of your choice, try adding the following snippet and generating your site:
<pre>
```python
#!/usr/bin/python3

from engine import RunForrestRun

"""Test code for syntax highlighting!"""

class Foo:
  def __init__(self, var):
    self.var = var
    self.run()

  def run(self):
    RunForrestRun()  # run along!
```
</pre>

The resulting `.html` file should have colorized output.

**Comment by davidhampgonsalves** [comment]
thanks @cardi for this explanation.
