### ISSUE TITLE
dates showing although not set

### ISSUE THREAD

**Issue by matiasandina** [davidhampgonsalves/hugo-black-and-light-theme#18]
I currently have 3 entries on my site: 1 post, and 2 pages. The pages have no date or title, just pure markdown or markdown + html. The site is showing entries as if they were posted on January 1 of 0001. What do I have to do to avoid this? Is there a way to make them disappear or have the landing page be `/posts`? (Although for some reason there is no index.html generated for `/posts`) 

[This is my site deployed](http://writing-matiasandina.netlify.com)

**Comment by matiasandina** [comment]
This was fixed on my personal repo (see faf12fa9bdb700bcdaad9d9777f3cc8ab2c7500c) I can provide a pull request if deemed necessary
https://github.com/matiasandina/writing

**Comment by davidhampgonsalves** [comment]
Thanks for reporting, this is now fixed.
