### ISSUE TITLE
Same IDs re-used in multiple places

### ISSUE THREAD

**Issue by hacklschorsch** [davidhampgonsalves/hugo-black-and-light-theme#19]
Thank you for this very nice theme! I have adopted it for my [personal blog](//florian.sesser.at/).

I only now saw that this theme re-uses the same ID attribute for multiple elements, for example can I see `<div id=date>` multiple times in the source code of the [theme demo page](https://themes.gohugo.io/theme/black-and-light/). This seems to [not be valid HTML](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute):

> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character.

Probably one can exchange many of the `id` attributes by `class` attributes of the same value, change the CSS selectors to match, and be done with it.

The [w3c html validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fthemes.gohugo.io%2Ftheme%2Fblack-and-light%2F) also recognizes this as a problem, plus some others. I can't say how bad any of those are, though.

[This thread](https://softwareengineering.stackexchange.com/questions/127178/two-html-elements-with-same-id-attribute-how-bad-is-it-really) has a list of things that can go wrong when re-using IDs.

**Comment by davidhampgonsalves** [comment]
thanks, fixed
