### ISSUE TITLE
RSS link doesn't validate

### ISSUE THREAD

**Issue by skyfaller** [davidhampgonsalves/hugo-black-and-light-theme#20]
When I ran my site through https://validator.w3.org/nu/ after updating to the latest version of the theme it choked on the atom link that you [installed in this commit](https://github.com/davidhampgonsalves/hugo-black-and-light-theme/commit/6659e02d85bfec8b7bc582330ac5fa723253292f):
```
    {{ with .OutputFormats.Get "RSS" }}
        {{ printf "<atom:link href=%q rel=\"self\" type=%q />" .Permalink .MediaType | safeHTML }}
    {{ end }}
```
The sample at https://gohugo.io/templates/rss/ validates and seems to work fine:
```
{{ range .AlternativeOutputFormats -}}
    {{ printf `<link rel="%s" type="%s" href="%s" title="%s" />` .Rel .MediaType.Type .Permalink $.Site.Title | safeHTML }}
{{ end -}}
```
Is there any reason not to use what the Hugo documentation recommends here?

**Comment by davidhampgonsalves** [comment]
probably b/c that was the old way of doing RSS. Thanks for reporting.
