### ISSUE TITLE
max-width: auto is not valid CSS

### ISSUE THREAD

**Issue by skyfaller** [davidhampgonsalves/hugo-black-and-light-theme#21]
[As far as I can tell, "auto" is not a valid value for "max-width".](https://stackoverflow.com/questions/23079720/is-max-widthauto-max-width100) It does not appear in any reference docs I can find, such as [the MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/max-width).

max-width: auto [occurs in your styling here](https://github.com/davidhampgonsalves/hugo-black-and-light-theme/blob/d5124d5ca244c0584bf1713e871a275fef33db41/layouts/partials/styles.html#L76): 
```
  pre code {
    display: inline;
    max-width: auto;
    padding: 0;
    margin: 0;
    overflow: visible;
    line-height: inherit;
    word-wrap: normal;
    background-color: transparent;
    border: 0;
  }
```

What were you trying to accomplish? What, if anything, should this CSS value be replaced with?

**Comment by davidhampgonsalves** [comment]
Thanks, removed.
