### ISSUE TITLE
install command is wrong

### ISSUE THREAD

**Issue by hloeffler** [davidhampgonsalves/hugo-black-and-light-theme#3]
see https://github.com/davidhampgonsalves/hugo-black-and-light-theme/pull/2

**Comment by hoelter** [comment]
I can confirm.

**Comment by rumyantseva** [comment]
+1

**Comment by davidhampgonsalves** [comment]
resolved in: https://github.com/davidhampgonsalves/hugo-black-and-light-theme/pull/2
