### ISSUE TITLE
Question on Referrer Policy

### ISSUE THREAD

**Issue by ghost** [davidhampgonsalves/hugo-black-and-light-theme#6]
Hello. Beautiful theme. I especially appreciate the screenshot presentation.

Question about the referrer policy in use. From what I was reading [on W3C](https://www.w3.org/TR/referrer-policy/#referrer-policy-no-referrer) using "no-referrer" will prevent the "Referer" [sic] header on same- and cross-domain HTTP requests. As a result, users of this theme who hyperlink to other sites will not appear in Google Analytics (and may not appear in the Search Consoles). There are also potential caching implications as well. Is the intention using the no-referrer Referral Policy to be incognito, so to speak, when linking to other sites, or are there other reasons? Just curious. I'd love to hear your thoughts. Best regards.

**Comment by davidhampgonsalves** [comment]
I didn't give it a lot of thought but I was prioritising my users privacy which is also why GA is disabled by default. I'd be open to changing it though.

I didn't think it would affect cachability though, can you expand on that?

**Comment by ghost** [comment]
From the W3C docs linked above:

> If a document at https://example.com/page.html sets a policy of ["no-referrer"](https://www.w3.org/TR/referrer-policy/#referrer-policy-no-referrer), then navigations to https://example.com/ (or any other URL) would send no [Referer](https://tools.ietf.org/html/rfc7231#section-5.5.2) header.

Following the `Referer` link lands on an IETF page which states the following in para 2 (emphasis mine):

> The Referer header field allows servers to generate back-links to
   other resources for simple analytics, logging, _optimized caching_,
   etc.

I'm not sure how to interpret that. But it did raise my eyebrow, so I thought I'd ask. Thanks for the info!
