### ISSUE TITLE
Next and previous post buttons reversed.

### ISSUE THREAD

**Issue by GAZ082** [davidhampgonsalves/hugo-black-and-light-theme#8]
Hi there. I found that the nav buttons of the posts are reversed. IE, the next post is on the left bottom corner instead of the left, and the previous post is on the right bottom.

My posts are sorted by weight. Is this intentional? If so, how can i reverse it?

Thanks.

**Comment by GAZ082** [comment]
:3

**Comment by davidhampgonsalves** [comment]
Sorry for the delay, I missed the notification. The next / previous button destinations are generated by hugo not the layout. See: https://github.com/davidhampgonsalves/hugo-black-and-light-theme/blob/master/layouts/_default/single.html#L14

This might help: https://discourse.gohugo.io/t/next-prev-based-on-menu-parent-and-weight/292
